name: "edit"
version: "1.0.0"
usage: "edit user specified values of a release"
description: "edit user specified values of a release"
command: "$HELM_PLUGIN_DIR/bin/edit"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install.sh"
